"""Writes the knowledge banks out as readable plain-text files.

The banks themselves are JSON under `~/Desktop/.shadow/` — compact, and shaped for
the code that assembles prompts. That's the wrong format for a person: it's a
hidden directory full of machine-oriented structures.

This module renders the same content as text under
`~/Desktop/Shadow/knowledgebank/`, next to the app's existing dated log folders,
so what the AI knows can be read, searched with grep, diffed, or pasted into a
document without touching JSON.

The text files are a **derived view, never the source**. They're overwritten on
every export; editing one changes nothing, because the next index run regenerates
it. That's stated in each file's header so nobody edits one expecting it to stick.
"""
from __future__ import annotations

import textwrap
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Union

from ..shadow_home import repo_id
from .depth import RepoDepth
from .general import GeneralDigest, GeneralKnowledgeBank
from .indexer import KnowledgeBank
from .manifests import summarize_dependencies
from .summaries import (
    SUMMARY_ARCHITECTURE,
    SUMMARY_ONBOARDING,
    SUMMARY_PATTERNS,
    load_summaries,
)

DEFAULT_EXPORT_DIR = Path("~/Desktop/Shadow/knowledgebank")

GENERAL_FILE = "general-knowledge-bank.txt"
INDEX_FILE = "README.txt"

_WRAP_WIDTH = 88

_DERIVED_NOTICE = (
    "This file is generated by Shadow and overwritten on every index run.\n"
    "Editing it has no effect — the knowledge banks live in ~/Desktop/.shadow/ as JSON."
)


def export_dir(root: Optional[Union[str, Path]] = None) -> Path:
    """Returns (without creating) the text-export directory."""
    return Path(root or DEFAULT_EXPORT_DIR).expanduser()


def _heading(text: str, level: int = 1) -> str:
    if level == 1:
        rule = "=" * min(len(text), _WRAP_WIDTH)
        return f"\n{text}\n{rule}\n"
    rule = "-" * min(len(text), _WRAP_WIDTH)
    return f"\n{text}\n{rule}\n"


def _paragraph(text: str) -> str:
    """Wraps prose to a readable width, preserving blank-line breaks."""
    if not text.strip():
        return ""
    blocks = []
    for block in text.strip().split("\n\n"):
        collapsed = " ".join(block.split())
        blocks.append(textwrap.fill(collapsed, width=_WRAP_WIDTH))
    return "\n\n".join(blocks) + "\n"


def _bullets(items: List[str], limit: Optional[int] = None) -> str:
    chosen = items[:limit] if limit else items
    lines = []
    for item in chosen:
        # Indent continuation lines so a long entry stays visually one bullet.
        wrapped = textwrap.fill(
            " ".join(str(item).split()), width=_WRAP_WIDTH, initial_indent="  - ",
            subsequent_indent="    ",
        )
        lines.append(wrapped)
    if limit and len(items) > limit:
        lines.append(f"    ... and {len(items) - limit} more")
    return "\n".join(lines) + "\n" if lines else ""


def _header(title: str, subtitle: str = "") -> str:
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    parts = [
        "=" * _WRAP_WIDTH,
        title,
        "=" * _WRAP_WIDTH,
        "",
        f"Generated: {stamp}",
    ]
    if subtitle:
        parts.append(subtitle)
    parts += ["", _DERIVED_NOTICE, ""]
    return "\n".join(parts)


# -- general bank -----------------------------------------------------------


def render_general_text(digest: GeneralDigest) -> str:
    """Renders the General Knowledge Bank as readable text."""
    out = [
        _header(
            "GENERAL KNOWLEDGE BANK",
            "Organizational context gathered from captured meetings and screen activity.",
        )
    ]

    if digest.is_empty:
        out.append(
            _paragraph(
                "Nothing captured yet. This bank fills up from meeting transcripts and "
                "screen OCR — enable capture on the Live Monitor tab, then update the "
                "bank from the Code tab."
            )
        )
        return "\n".join(out)

    out.append(_heading("Coverage"))
    days = digest.days_covered
    span = f"{days[0]} to {days[-1]}" if len(days) > 1 else (days[0] if days else "unknown")
    out.append(
        _paragraph(
            f"{digest.event_count} captured events across {len(days)} day(s) ({span}). "
            f"Last updated {digest.updated_at or 'unknown'}."
        )
    )
    if digest.type_counts:
        ranked = sorted(digest.type_counts.items(), key=lambda kv: -kv[1])
        out.append(_bullets([f"{name}: {count}" for name, count in ranked], limit=12))

    for title, items in (
        ("Decisions", digest.decisions),
        ("Action items", digest.action_items),
        ("Recurring problems", digest.problems),
        ("Meeting notes", digest.meetings),
    ):
        out.append(_heading(title, level=2))
        if items:
            out.append(
                _bullets(
                    [f"({item.timestamp.split('T')[0]}) {item.text}" for item in items],
                    limit=40,
                )
            )
        else:
            # Say why it's empty rather than leaving a blank section — for
            # decisions and problems this is usually the classifier, not a lack of
            # relevant activity.
            out.append(
                _paragraph(
                    "None recorded. Captured speech is classified as a meeting by default "
                    "(see events/classifier.py), so decision and problem statements inside "
                    "a transcript may not be separated out yet."
                )
                if title in ("Decisions", "Recurring problems")
                else _paragraph("None recorded.")
            )

    if digest.glossary:
        out.append(_heading("Project vocabulary", level=2))
        out.append(
            _paragraph(
                "Terms that recur in your captured activity, most frequent first."
            )
        )
        out.append(_bullets([f"{term} ({count})" for term, count in digest.glossary.items()],
                            limit=60))

    if digest.tickets:
        out.append(_heading("Tickets referenced", level=2))
        out.append(_bullets([f"{key} ({count})" for key, count in digest.tickets.items()],
                            limit=30))

    if digest.applications or digest.hosts:
        out.append(_heading("Applications and sites", level=2))
        out.append(_bullets(list(digest.applications) + list(digest.hosts), limit=30))

    return "\n".join(out)


def export_general(
    event_store,
    shadow_root: Optional[Union[str, Path]] = None,
    dest_dir: Optional[Union[str, Path]] = None,
) -> Optional[Path]:
    """Writes the general bank as text. Returns the file path, or None if unbuilt."""
    bank = GeneralKnowledgeBank(event_store, shadow_root)
    digest = bank.load()
    directory = export_dir(dest_dir)
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / GENERAL_FILE
    target.write_text(render_general_text(digest), encoding="utf-8")
    return target


# -- repo bank --------------------------------------------------------------


def render_repo_text(bank: KnowledgeBank) -> str:
    """Renders one repository's Knowledge Bank as readable text."""
    meta = bank.load_meta()
    if meta is None:
        return _header("REPOSITORY KNOWLEDGE BANK") + _paragraph(
            "This repository has not been indexed yet."
        )

    entries = bank.load_files()
    outline = bank.load_outline()
    depth: RepoDepth = bank.load_depth()
    manifests = bank.load_manifests()
    readme, docs = bank.load_docs()
    summaries = load_summaries(bank)

    out = [_header(f"REPOSITORY KNOWLEDGE BANK — {meta.name}", meta.root_path)]

    out.append(_heading("Overview"))
    facts = [
        f"{meta.file_count} indexed files",
        f"branch: {meta.git.branch or 'n/a'}",
        f"last indexed: {meta.updated_at}",
    ]
    if meta.truncated:
        facts.append("index truncated at the configured file limit")
    out.append(_bullets(facts))

    languages = outline.get("by_language", {})
    if languages:
        ranked = sorted(languages.items(), key=lambda kv: -kv[1])
        out.append(_paragraph("Languages: " + ", ".join(f"{n} ({c})" for n, c in ranked[:10])))

    # LLM prose, when it has been generated. Labelled as generated so it isn't
    # mistaken for something a person wrote and verified.
    for key, title in (
        (SUMMARY_ARCHITECTURE, "Architecture"),
        (SUMMARY_PATTERNS, "Conventions and patterns"),
        (SUMMARY_ONBOARDING, "Getting started"),
    ):
        entry = summaries.get(key)
        if entry and entry.text:
            out.append(_heading(f"{title} (AI-generated summary)"))
            out.append(_paragraph(entry.text))
            out.append(_paragraph(f"[written by {entry.model or 'the local model'} on "
                                  f"{entry.generated_at or 'unknown date'}]"))

    if depth.frameworks:
        out.append(_heading("Frameworks and libraries"))
        out.append(_bullets(depth.frameworks))
    dependency_text = summarize_dependencies(manifests, limit=60)
    if dependency_text:
        out.append(_heading("Declared dependencies", level=2))
        out.append(dependency_text + "\n")

    if depth.integrations:
        out.append(_heading("External systems"))
        out.append(_paragraph("Inferred from the clients this code imports."))
        out.append(_bullets(depth.integrations))

    if depth.routes:
        out.append(_heading("HTTP routes"))
        out.append(_bullets([route.label for route in depth.routes], limit=80))

    if depth.env_vars:
        out.append(_heading("Environment variables read"))
        out.append(_bullets(depth.env_vars, limit=50))

    if depth.hub_modules:
        out.append(_heading("Widely-used modules"))
        out.append(_paragraph("Changing these has the widest reach."))
        out.append(
            _bullets(
                [
                    f"{path} — imported by {len(depth.imported_by.get(path, []))} file(s)"
                    for path in depth.hub_modules
                ],
                limit=25,
            )
        )

    if depth.imports:
        out.append(_heading("Module relationships"))
        out.append(_paragraph("Which in-repo modules each file imports."))
        lines = []
        for path in sorted(depth.imports)[:120]:
            lines.append(f"{path} -> {', '.join(depth.imports[path])}")
        out.append(_bullets(lines, limit=120))

    if outline.get("entrypoints"):
        out.append(_heading("Entry points", level=2))
        out.append(_bullets(outline["entrypoints"], limit=20))

    if depth.hot_files:
        out.append(_heading("Most-changed files"))
        out.append(
            _bullets(
                [f"{item['path']} — {item['commits']} commit(s)" for item in depth.hot_files],
                limit=30,
            )
        )

    if depth.recent_commits:
        out.append(_heading("Recent commits", level=2))
        out.append(
            _bullets(
                [f"{c['sha']} {c['subject']} ({c['author']}, {c['when']})"
                 for c in depth.recent_commits],
                limit=20,
            )
        )

    if depth.test_files:
        out.append(_heading("Tests", level=2))
        out.append(_bullets(depth.test_files, limit=40))
    if depth.config_files:
        out.append(_heading("Configuration and infrastructure", level=2))
        out.append(_bullets(depth.config_files, limit=30))

    if readme is not None:
        out.append(_heading("README excerpt"))
        out.append(_paragraph(readme.excerpt[:2500]))
    if docs:
        out.append(_heading("Documentation found", level=2))
        out.append(_bullets([f"{doc.path} — {doc.title}" for doc in docs], limit=20))

    out.append(_heading("API outline"))
    out.append(
        _paragraph(
            "Symbols defined per file. Python entries come from a real parser; other "
            "languages are matched by pattern and marked approximate."
        )
    )
    out.append(_render_symbols(entries))

    return "\n".join(out)


def _render_symbols(entries: dict, max_files: int = 200) -> str:
    lines: List[str] = []
    for path in sorted(entries):
        entry = entries[path]
        if not entry.symbols:
            continue
        suffix = "  (approximate)" if entry.parse == "regex" else ""
        lines.append(f"\n{path}{suffix}")
        for symbol in entry.symbols[:40]:
            signature = symbol.signature or f"{symbol.kind} {symbol.name}"
            doc = f"  # {symbol.doc}" if symbol.doc else ""
            lines.append(f"    {signature}{doc}")
        if len(lines) > max_files * 12:
            lines.append("\n... (truncated)")
            break
    return "\n".join(lines) + "\n" if lines else "No symbols extracted.\n"


def _safe_filename(name: str) -> str:
    cleaned = "".join(c if c.isalnum() or c in "._-" else "-" for c in name).strip("-.")
    return cleaned or "repo"


def export_repo(
    project_path: Union[str, Path],
    shadow_root: Optional[Union[str, Path]] = None,
    dest_dir: Optional[Union[str, Path]] = None,
) -> Optional[Path]:
    """Writes one repository's bank as text. Returns the path, or None if unindexed."""
    bank = KnowledgeBank(project_path, shadow_root)
    if not bank.exists:
        return None
    directory = export_dir(dest_dir)
    directory.mkdir(parents=True, exist_ok=True)
    # Includes the same path hash the bank directory uses, so two repositories
    # with the same folder name don't overwrite each other's export.
    target = directory / f"{_safe_filename(repo_id(project_path))}.txt"
    target.write_text(render_repo_text(bank), encoding="utf-8")
    return target


def write_index(dest_dir: Optional[Union[str, Path]] = None) -> Path:
    """Writes a README listing what's in the export directory."""
    directory = export_dir(dest_dir)
    directory.mkdir(parents=True, exist_ok=True)
    files = sorted(p.name for p in directory.glob("*.txt") if p.name != INDEX_FILE)
    body = [
        _header("SHADOW KNOWLEDGE BANKS (text export)"),
        _paragraph(
            "Plain-text views of what Shadow's local AI knows. The authoritative copies "
            "are JSON under ~/Desktop/.shadow/; these are regenerated on every index run."
        ),
        _heading("Files"),
        _bullets(
            [
                f"{GENERAL_FILE} — organizational context from meetings and screen capture"
                if name == GENERAL_FILE
                else f"{name} — one repository's architecture, dependencies, APIs and structure"
                for name in files
            ]
        )
        or _paragraph("Nothing exported yet."),
    ]
    target = directory / INDEX_FILE
    target.write_text("\n".join(body), encoding="utf-8")
    return target
